<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PCE Interaction terms for R – PCE</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PCE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-1" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-1">    
        <li>
    <a class="dropdown-item" href="./PCE_Summarystats_Quarto.html">
 <span class="dropdown-text">Summary Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Graphics_Quarto.html">
 <span class="dropdown-text">Graphics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-2" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-2">    
        <li>
    <a class="dropdown-item" href="./PCE_Ttest_Quarto.html">
 <span class="dropdown-text">T-test</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-3" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-3">    
        <li>
    <a class="dropdown-item" href="./PCE_Prop_Quarto.html">
 <span class="dropdown-text">Proportions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Survival_Quarto.html">
 <span class="dropdown-text">Survival</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Power_Quarto.html"> 
<span class="menu-text">P5_Power</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_MH_Quarto.html"> 
<span class="menu-text">P6_Mantel_Haenszel</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Corr_Quarto.html"> 
<span class="menu-text">P7_Correlation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Simple_Quarto.html"> 
<span class="menu-text">P7_Simple</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Logistic_Quarto.html"> 
<span class="menu-text">P8_Logistic</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./PCE_Interaction_Quarto.html" aria-current="page"> 
<span class="menu-text">P8_Interaction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Cox_Quarto.html"> 
<span class="menu-text">P9_Cox</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_OnewayANOVA_Quarto.html"> 
<span class="menu-text">P9_Oneway_ANOVA</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_Pairwise_Quarto.html"> 
<span class="menu-text">P9_Pairwise</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_PairedCont_Quarto.html"> 
<span class="menu-text">P10_Paired_Continuous</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./PCE_PairedDich_Quarto.html"> 
<span class="menu-text">P10_Paired_Dichotomous</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#interaction-terms" id="toc-interaction-terms" class="nav-link active" data-scroll-target="#interaction-terms">Interaction terms</a>
  <ul class="collapse">
  <li><a href="#multiple-regression-review" id="toc-multiple-regression-review" class="nav-link" data-scroll-target="#multiple-regression-review">Multiple regression review</a></li>
  <li><a href="#interaction-term" id="toc-interaction-term" class="nav-link" data-scroll-target="#interaction-term">Interaction term</a></li>
  <li><a href="#interaction-terms-in-logistic-regression" id="toc-interaction-terms-in-logistic-regression" class="nav-link" data-scroll-target="#interaction-terms-in-logistic-regression">Interaction terms in logistic regression</a></li>
  <li><a href="#relationship-to-mantel-haentzel-tests" id="toc-relationship-to-mantel-haentzel-tests" class="nav-link" data-scroll-target="#relationship-to-mantel-haentzel-tests">Relationship to Mantel-Haentzel tests</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PCE Interaction terms for R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="interaction-terms" class="level2">
<h2 class="anchored" data-anchor-id="interaction-terms">Interaction terms</h2>
<p>Goal: This practicum will go over how to investigate interaction terms in linear and logistic regression using R</p>
<section id="multiple-regression-review" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-review">Multiple regression review</h3>
<p>In class, we described how to investigate interaction terms. An interaction term implies that the effect of one predictor on the outcome is affected by another predictor in the model. Even though an interaction has a different interpretation than regression coefficients from previous models, the approach for testing for an interaction term is still based on regression coefficients.</p>
<p>For this practicum, we investigate the BPF dataset that we have used in previous practicums (bpf dataset). Please load this dataset into R and call the dataset <em>bpf_data</em>. In previous practicums, we have investigated the effect of disease activity on BPF controlling for age using the following regression equation where activity=0 for those without activity and activity=1 for those with activity:</p>
<p><span class="math display">\[
E(BPF_i)=\beta_0+\beta_1*activity_i+\beta_2*age_i
\]</span></p>
<p>In this model, there is an association between both activity <span class="math inline">\((\beta_1)\)</span> and age <span class="math inline">\((\beta_2)\)</span>. In particular, the regression equation in those without activity is:</p>
<p><span class="math display">\[
E(BPF_i)=\beta_0+\beta_2*age_i
\]</span></p>
<p>The regression equation in those with activity is:</p>
<p><span class="math display">\[
E(BPF_i)=(\beta_0+\beta_1)+\beta_2*age_i
\]</span> Note that in the two models, the association between age and BPF is the same in each group <span class="math inline">\((\beta_2)\)</span>, but the intercepts in the activity group and the no activity group are different. Therefore, this model assumes parallel lines with different intercepts.</p>
<p>To complete this regression in R, we use the following commands.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mod1<span class="ot">&lt;-</span><span class="fu">lm</span>(bpf <span class="sc">~</span> activity<span class="sc">+</span>age, <span class="at">data=</span>bpf_data)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bpf ~ activity + age, data = bpf_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.066041 -0.026283 -0.001167  0.028317  0.075897 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.9419854  0.0389932  24.158  &lt; 2e-16 ***
activity     0.0171886  0.0187867   0.915  0.36864    
age         -0.0026207  0.0008363  -3.134  0.00424 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04073 on 26 degrees of freedom
Multiple R-squared:  0.3538,    Adjusted R-squared:  0.3041 
F-statistic: 7.117 on 2 and 26 DF,  p-value: 0.003427</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %        97.5 %
(Intercept)  0.861833605  1.0221371331
activity    -0.021428078  0.0558052356
age         -0.004339732 -0.0009016238</code></pre>
</div>
</div>
<p>The resulting regression equation from this analysis is</p>
<p><span class="math display">\[
\hat{BPF}_i=\hat{\beta}_0+\hat{\beta}_1*activity_i+\hat{\beta}_2*age_i
\]</span></p>
<p>with <span class="math inline">\(\hat{\beta}_0=\)</span> 0.942, <span class="math inline">\(\hat{\beta}_1=\)</span> 0.0172, and <span class="math inline">\(\hat{\beta}_2=\)</span> -0.0026.</p>
<p>The corresponding graph for this regression equation can be created in R using the following commands:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>bpf_data<span class="sc">$</span>yhat<span class="ot">&lt;-</span><span class="fu">predict</span>(mod1)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bpf_data<span class="ot">&lt;-</span> bpf_data[<span class="fu">order</span>(bpf_data<span class="sc">$</span>age),]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bpf_data<span class="sc">$</span>age,bpf_data<span class="sc">$</span>bpf,<span class="at">type=</span><span class="st">"n"</span>,<span class="at">xlab=</span><span class="st">"Age (years)"</span>,<span class="at">ylab=</span><span class="st">"BPF"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],bpf_data<span class="sc">$</span>bpf[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],bpf_data<span class="sc">$</span>bpf[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],bpf_data<span class="sc">$</span>yhat[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],bpf_data<span class="sc">$</span>yhat[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],<span class="at">col=</span><span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PCE_Interaction_Quarto_files/figure-html/Multiple lm graph-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Note that this regression equation assumes equal slopes for the activity group and the no activity group. In previous practicums, we have discussed how to test whether there was an association between activity and BPF controlling for age based on this model.</p>
</section>
<section id="interaction-term" class="level3">
<h3 class="anchored" data-anchor-id="interaction-term">Interaction term</h3>
<p>It might be important to assess whether the change in BPF with age was different in the activity group and no activity group. In other words, we might want to assess if there is an interaction between age and activity in terms of the association with BPF. The regression equation in this case is given by:</p>
<p><span class="math display">\[
E(BPF_i)=\beta_0+\beta_1*activity_i+\beta_2*age_i+\beta_3*activity_i*age_i
\]</span> Based on this model, the regression equation for the no activity group is: <span class="math display">\[
E(BPF_i)=\beta_0+\beta_2*age_i
\]</span></p>
<p>The regression equation for the activity group is: <span class="math display">\[
E(BPF_i)=(\beta_0+\beta_1)+(\beta_2+\beta_3)*age_i
\]</span> In this model, the slope and intercept were different for the two groups. Our focus for this example is to assess whether the association with age is different in the two groups. If the association with age is different, the difference in the slopes <span class="math inline">\((\beta_3)\)</span> would be different than 0. Therefore, our focus will be this regression coefficient. As usual, we can complete the first three steps of our hypothesis test before we run the regression in R:</p>
<ol type="1">
<li><p>State estimand of interest and null hypothesis: Difference in slopes (i.e.&nbsp;interaction between age and activity; <span class="math inline">\(\beta_3\)</span>); <span class="math inline">\(H_0: \beta_3=0\)</span></p></li>
<li><p>State type of data: Continuous outcome, dichotomous/continuous explanatory variable</p></li>
<li><p>Determine appropriate statistical test: Multiple linear regression</p></li>
</ol>
<p>There are a couple of ways to investigate an interaction using R. The first is to directly create the appropriate interaction term. I prefer this approach since I know exactly how the variable has been created. We would like a variable that is equal to age for the activity group and equal to 0 for the no activity group. This can be created using the following command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>bpf_data<span class="sc">$</span>inter<span class="ot">&lt;-</span>bpf_data<span class="sc">$</span>age<span class="sc">*</span>bpf_data<span class="sc">$</span>activity</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Since <em>activity=0</em> for no activity group, the variable <em>inter</em> will equal 0 for no activity group because 0 times age is always equal to 0. Since <em>activity=1</em> for the activity group, the variable <em>inter</em> will equal age for the activity group because 1 times age is always equal to age. Now, we can add this term to our lm command.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mod2<span class="ot">&lt;-</span><span class="fu">lm</span>(bpf <span class="sc">~</span> activity<span class="sc">+</span>age<span class="sc">+</span>inter, <span class="at">data=</span>bpf_data)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bpf ~ activity + age + inter, data = bpf_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.071989 -0.026672 -0.000472  0.026953  0.075640 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.9556349  0.0478778  19.960  &lt; 2e-16 ***
activity    -0.0197127  0.0753469  -0.262  0.79575    
age         -0.0029210  0.0010353  -2.821  0.00924 ** 
inter        0.0009147  0.0018070   0.506  0.61714    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04133 on 25 degrees of freedom
Multiple R-squared:  0.3603,    Adjusted R-squared:  0.2836 
F-statistic: 4.694 on 3 and 25 DF,  p-value: 0.009831</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   2.5 %       97.5 %
(Intercept)  0.857028615  1.054241130
activity    -0.174892602  0.135467197
age         -0.005053254 -0.000788680
inter       -0.002806796  0.004636233</code></pre>
</div>
</div>
<p>Based on this output, we get the following regression equation:</p>
<p><span class="math display">\[
\hat{BPF}_i=\hat{\beta}_0+\hat{\beta}_1*activity_i+\hat{\beta}_2*age_i+\hat{\beta}_3*activity_i*age_i
\]</span></p>
<p>where <span class="math inline">\(\hat{\beta}_0=\)</span> 0.956, <span class="math inline">\(\hat{\beta}_1=\)</span> -0.0197, <span class="math inline">\(\hat{\beta}_2=\)</span> -0.0029, and <span class="math inline">\(\hat{\beta}_3=\)</span> 9^{-4}</p>
<p>Based on this model, the regression equation for the no activity group is: <span class="math display">\[
\hat{BPF}=\hat{\beta}_0+\hat{\beta}_2*age_i
\]</span></p>
<p>where the intercept for the no activity group is <span class="math inline">\(\hat{\beta}_0\)</span> 0.956, and the slope for the not activity group is <span class="math inline">\(\hat{\beta}_2=\)</span> -0.0029.</p>
<p>The regression equation for the activity group is: <span class="math display">\[
\hat{BPF}_i=(\hat{\beta}_0+\hat{\beta}_1)+(\hat{\beta}_2+\hat{\beta}_3)*age_i
\]</span> where the intercept fof the activity group is <span class="math inline">\(\hat{\beta}_0+\hat{\beta}_1=\)</span> 0.956 <span class="math inline">\(+\)</span> -0.0197=0.9363, and the slope in the activity group is <span class="math inline">\(\hat{\beta}_2+\hat{\beta}_3=\)</span> -0.0029 <span class="math inline">\(+\)</span> 9^{-4}=-0.002</p>
<p>Note that the difference in the slope for the activity group and the no activity group is 9^{-4}, which is the estimated <span class="math inline">\(\hat{\beta}_3\)</span>. The graph of our predicted values from this model can be created using the following commands:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bpf_data<span class="sc">$</span>yhat2<span class="ot">&lt;-</span><span class="fu">predict</span>(mod2)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>bpf_data<span class="ot">&lt;-</span> bpf_data[<span class="fu">order</span>(bpf_data<span class="sc">$</span>age),]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bpf_data<span class="sc">$</span>age,bpf_data<span class="sc">$</span>bpf,<span class="at">type=</span><span class="st">"n"</span>,<span class="at">xlab=</span><span class="st">"Age (years)"</span>,<span class="at">ylab=</span><span class="st">"BPF"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],bpf_data<span class="sc">$</span>bpf[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],bpf_data<span class="sc">$</span>bpf[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],<span class="at">col=</span><span class="st">"red"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],bpf_data<span class="sc">$</span>yhat2[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">1</span>],<span class="at">col=</span><span class="st">"blue"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(bpf_data<span class="sc">$</span>age[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],bpf_data<span class="sc">$</span>yhat2[bpf_data<span class="sc">$</span>activity<span class="sc">==</span><span class="dv">0</span>],<span class="at">col=</span><span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PCE_Interaction_Quarto_files/figure-html/Interaction graph-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the graph, we can see that the slopes are only a little different in the two groups. The p-value for the hypothesis test of interest is provided in the R output above (<span class="math inline">\(p=\)</span> 0.617). Now, we can finish our analysis.</p>
<ol start="4" type="1">
<li><p>State summary statistics if possible: estimated <span class="math inline">\(\hat{\beta}_3 =\)</span> 9^{-4}</p></li>
<li><p>Calculate confidence interval and p-value (stat package): -0.0028, 0.0046; <span class="math inline">\(p=\)</span> 0.617</p></li>
<li><p>The estimated difference in the slopes was 9^{-4}, and the range of plausible values for the difference in the slopes is from -0.0028 to 0.0046. There is limited evidence of a statistical interaction based on our sample.</p></li>
</ol>
<p>Since there was a limited difference in the slope comparing the activity group and the no activity group, we can remove this term from the model.</p>
<p>In addition to this approach, R allows us to investigate interactions without generating new variables, but we must be more careful in our coding. In particular, we must tell R which variables are categorical/dichotomous and which variables are continuous. For categorical/dichotomous variables, we add factor prior to the variable name. The new regression command is given here:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mod3<span class="ot">&lt;-</span><span class="fu">lm</span>(bpf <span class="sc">~</span> <span class="fu">factor</span>(activity)<span class="sc">+</span>age<span class="sc">+</span><span class="fu">factor</span>(activity)<span class="sc">:</span>age, <span class="at">data=</span>bpf_data)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = bpf ~ factor(activity) + age + factor(activity):age, 
    data = bpf_data)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.071989 -0.026672 -0.000472  0.026953  0.075640 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            0.9556349  0.0478778  19.960  &lt; 2e-16 ***
factor(activity)1     -0.0197127  0.0753469  -0.262  0.79575    
age                   -0.0029210  0.0010353  -2.821  0.00924 ** 
factor(activity)1:age  0.0009147  0.0018070   0.506  0.61714    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04133 on 25 degrees of freedom
Multiple R-squared:  0.3603,    Adjusted R-squared:  0.2836 
F-statistic: 4.694 on 3 and 25 DF,  p-value: 0.009831</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mod3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             2.5 %       97.5 %
(Intercept)            0.857028615  1.054241130
factor(activity)1     -0.174892602  0.135467197
age                   -0.005053254 -0.000788680
factor(activity)1:age -0.002806796  0.004636233</code></pre>
</div>
</div>
<p>The <em>factor(activity):age</em> part of the command indicates to R that we would like to investigate the interaction between these two variables. Note that the results from this command are exactly the same as from the previous analysis. The <em>factor(activity)1</em> in the regression output indicates that the coefficient is for patients with <em>activity=1</em>. This demonstrates that R is using no activity group as the reference group. Also, the <em>factor(activity)1:age</em> indicates that the coefficient is the difference in the slopes comparing the disease activity group to the no disease activity group. This coding can be helpful if you have a categorical variable with many levels.</p>
</section>
<section id="interaction-terms-in-logistic-regression" class="level3">
<h3 class="anchored" data-anchor-id="interaction-terms-in-logistic-regression">Interaction terms in logistic regression</h3>
<p>Let’s return to the Logistic_regression dataset. In the logistic regression lab, we investigated a couple of univariate relationships between variables and the probability of progression in MS patients. In addition to these analyses, we might be interested in whether the effect of one variable changes in the presence of a second variable. As we learned with linear regression, we can fit interaction terms to investigate this specific hypothesis. In this case, we would like to know if the association between SNP and progression is different in disease activity group and no disease activity group. Here is the logistic regression model that we would like to fit</p>
<p><span class="math display">\[
log(Odds_i)=log(\frac{p_i}{1-p_i})=\beta_0+\beta_1*SNP_i+\beta_2*activity+\beta_3*SNP_i*activity_i
\]</span></p>
<p>To investigate this hypothesis, we must create the interaction term and then fit the following model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Logistic_regression<span class="sc">$</span>inter<span class="ot">&lt;-</span> Logistic_regression<span class="sc">$</span>activity<span class="sc">*</span> Logistic_regression<span class="sc">$</span>snp</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>mod4<span class="ot">&lt;-</span><span class="fu">glm</span>(prog<span class="sc">~</span> snp<span class="sc">+</span> activity<span class="sc">+</span> inter, <span class="at">data=</span>Logistic_regression, <span class="at">family=</span>binomial)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = prog ~ snp + activity + inter, family = binomial, 
    data = Logistic_regression)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.07944    0.33540  -6.200 5.65e-10 ***
snp          0.38485    0.49398   0.779    0.436    
activity     0.04256    0.69950   0.061    0.951    
inter        0.18570    1.01542   0.183    0.855    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 147.96  on 189  degrees of freedom
Residual deviance: 146.89  on 186  degrees of freedom
AIC: 154.89

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.default</span>(mod4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) -2.7368176 -1.422065
snp         -0.5833324  1.353024
activity    -1.3284283  1.413548
inter       -1.8044810  2.175879</code></pre>
</div>
</div>
<p>Based on these results, we can complete our hypothesis test:</p>
<ol type="1">
<li><p>State estimand of interest and null hypothesis: Difference in association between SNP and progression in the disease activity group compared to the no disease activity group (<span class="math inline">\(\beta_3\)</span>); <span class="math inline">\(H_0: \beta_3=0\)</span></p></li>
<li><p>State type of data: Dichotomous outcome, dichotomous explanatory variable</p></li>
<li><p>Determine appropriate statistical test: Logistic regression</p></li>
<li><p>State summary statistics if possible: <span class="math inline">\(\hat{\beta}_3=\)</span> 0.186</p></li>
<li><p>Calculate confidence interval and p-value (stat package): (-1.804, 2.176); <span class="math inline">\(p=\)</span> 0.855</p></li>
<li><p>The estimated difference in the association is 0.186, and the range of plausible values is from -1.804 to 2.176. No difference in association between SNP and progression in the activity group and no activity group is included in the plausible values.</p></li>
</ol>
</section>
<section id="relationship-to-mantel-haentzel-tests" class="level3">
<h3 class="anchored" data-anchor-id="relationship-to-mantel-haentzel-tests">Relationship to Mantel-Haentzel tests</h3>
<p>When we want to control for the potential confounding effect of activity, we could use a Mantel-Haentzel approach. This approach creates a 2x2 table for each group and then combines across the tables. To perform this analysis in R, we use the following command:</p>
<p>The output from this analysis shows many things. First, the crude and Mantel-Haenszel adjusted RR (green arrow) and OR (blue arrow) are reported. In the middle, there is a “Test for homogeneity” for both the RR and OR. This test is asking whether the effect of SNP on progression is the same in the two groups. Note that there is limited evidence that the effect of SNP is different in the two groups for the RR (p=0.861, orange arrow) and the OR (p=0.861, red arrow). Please note that this is the same p-value and conclusion that we arrived at when we tested for an interaction between activity and SNP in our logistic regression model (orange arrow above). The Mantel-Haenszel test and logistic regression provide two alternative ways to think about the same hypothesis.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>