<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>PCE Practicum Proportions for R – PCE</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PCE</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-1" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 1</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-1">    
        <li>
    <a class="dropdown-item" href="./PCE_Summarystats_Quarto.html">
 <span class="dropdown-text">Summary Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Graphics_Quarto.html">
 <span class="dropdown-text">Graphics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-2" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 2</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-2">    
        <li>
    <a class="dropdown-item" href="./PCE_Ttest_Quarto.html">
 <span class="dropdown-text">T-test</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-3" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 3</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-3">    
        <li>
    <a class="dropdown-item" href="./PCE_Prop_Quarto.html">
 <span class="dropdown-text">Proportions</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Survival_Quarto.html">
 <span class="dropdown-text">Survival</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-4" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 4</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-4">    
        <li>
    <a class="dropdown-item" href="./PCE_Power_Quarto.html">
 <span class="dropdown-text">Power</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-5" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 5</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-5">    
        <li>
    <a class="dropdown-item" href="./PCE_MH_Quarto.html">
 <span class="dropdown-text">Mantel Haenszel</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-6" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 6</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-6">    
        <li>
    <a class="dropdown-item" href="./PCE_Corr_Quarto.html">
 <span class="dropdown-text">Correlation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Simple_Quarto.html">
 <span class="dropdown-text">Simple Linear Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-8" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 8</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-8">    
        <li>
    <a class="dropdown-item" href="./PCE_Logistic_Quarto.html">
 <span class="dropdown-text">Logistic Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Interaction_Quarto.html">
 <span class="dropdown-text">Interaction terms</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-9" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 9</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-9">    
        <li>
    <a class="dropdown-item" href="./PCE_Cox_Quarto.html">
 <span class="dropdown-text">Cox Regression</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_OnewayANOVA_Quarto.html">
 <span class="dropdown-text">Oneway ANOVA</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_Pairwise_Quarto.html">
 <span class="dropdown-text">Pairwise comparisons</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-practicum-10" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Practicum 10</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-practicum-10">    
        <li>
    <a class="dropdown-item" href="./PCE_PairedCont_Quarto.html">
 <span class="dropdown-text">Paired Continuous Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./PCE_PairedDich_Quarto.html">
 <span class="dropdown-text">Paired Dichotomous Data</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#analysis-of-proportions" id="toc-analysis-of-proportions" class="nav-link active" data-scroll-target="#analysis-of-proportions">Analysis of proportions</a></li>
  <li><a href="#program-in-clinical-effectiveness" id="toc-program-in-clinical-effectiveness" class="nav-link" data-scroll-target="#program-in-clinical-effectiveness">Program in Clinical Effectiveness</a>
  <ul class="collapse">
  <li><a href="#confidence-intervals-for-a-single-proportion" id="toc-confidence-intervals-for-a-single-proportion" class="nav-link" data-scroll-target="#confidence-intervals-for-a-single-proportion">Confidence intervals for a single proportion</a></li>
  <li><a href="#two-sample-test-of-proportions" id="toc-two-sample-test-of-proportions" class="nav-link" data-scroll-target="#two-sample-test-of-proportions">Two sample test of proportions</a></li>
  <li><a href="#chi-squared-test" id="toc-chi-squared-test" class="nav-link" data-scroll-target="#chi-squared-test">Chi-squared test</a></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test">Fisher’s exact test</a></li>
  <li><a href="#estimates-of-association" id="toc-estimates-of-association" class="nav-link" data-scroll-target="#estimates-of-association">Estimates of association</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PCE Practicum Proportions for R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="analysis-of-proportions" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-proportions">Analysis of proportions</h2>
</section>
<section id="program-in-clinical-effectiveness" class="level2">
<h2 class="anchored" data-anchor-id="program-in-clinical-effectiveness">Program in Clinical Effectiveness</h2>
<p>Goal: This practicum will go over how to do analysis of proportions in R.</p>
<section id="confidence-intervals-for-a-single-proportion" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals-for-a-single-proportion">Confidence intervals for a single proportion</h3>
<p>For this analysis, we will use the MSQOL dataset. Please read this dataset into R.</p>
<p>We would like to estimate the proportion of RRMS patients with fatigue scores of at least 40. To calculate a confidence interval for this proportion, we will dichotomize fatigue using 40 as the cut-off. First, we will create a new variable called <em>fatiglevel</em>. We will assign <em>fatiglevel=0</em> if fatigue score is less than 40 and <em>fatiglevel=1</em> if fatigue score is greater than or equal 40. In R, a shorthand approach for creating this variable is to use the <em>ifelse</em> command. First, we must provide a name of the new variable that we are creating, which is <em>fatiglevel</em> (<em>msqol$fatiglevel</em>). Then, we will use the <em>ifelse</em> command, which has three parts. The first part is the condition that we are testing (<em>msqol$fatig&gt;=40</em>). If the condition is true, <em>fatiglevel</em> will be assigned the value in the second part, which is 1 in this case. If the condition is false, <em>fatiglevel</em> will be assigned the value in the third part, which is 0. Now, we can calculate the number and proportion of subject with and without high fatigue.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>msqol<span class="sc">$</span>fatiglevel<span class="ot">&lt;-</span><span class="fu">ifelse</span>(msqol<span class="sc">$</span>fatig<span class="sc">&gt;=</span><span class="dv">40</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1 
208  44 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        0         1 
0.8253968 0.1746032 </code></pre>
</div>
</div>
<p>The estimated proportion of patients with fatigue score greater than or equal to 40 is <span class="math inline">\(\hat{p}=\)</span> 0.175.</p>
<p>To calculate the exact binomial confidence interval for the proportion, we can use the <em>binom.test</em> command. For this command, we can specify the number of successes in the first part of the command and the number of observations in the second part. Note that <em>table(msqol$fatiglevel)[2]</em> is one approach to calculate the number of patients with fatigue score greater than or equal to 40, and <em>sum(table(msqol$fatiglevel))</em> is one approach to calculate the total number of observations with a fatigue score.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="at">x=</span><span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel)[<span class="dv">2</span>],<span class="at">n=</span><span class="fu">sum</span>(<span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Exact binomial test

data:  table(msqol$fatiglevel)[2] and sum(table(msqol$fatiglevel))
number of successes = 44, number of trials = 252, p-value &lt; 2.2e-16
alternative hypothesis: true probability of success is not equal to 0.5
95 percent confidence interval:
 0.1298262 0.2272180
sample estimates:
probability of success 
             0.1746032 </code></pre>
</div>
</div>
<p>The estimated proportion is the same as above (<span class="math inline">\(\hat{p}=\)</span> 0.175) and the 95% confidence interval is shown as well (0.13, 0.227). Note that a hypothesis test for the null hypothesis that the true probability of success is equal to 0.5 is also provided. Often, this hypothesis test is not of interest so be careful interpreting this p-value. You can change the null hypothesis to be 0.2, which was the hypothesis from class, by adding <span class="math inline">\(p=0.2\)</span> to the end of the command. Please see <em>?binom.test</em> for more information.</p>
<p>As described in lecture, other potential confidence intervals are sometimes used as well and these are easily implemented in R. For example, the Wilson confidence interval, which is recommended by many authors, can be calculated using the <em>prop.test</em> command. Note that this command is very similar to the <em>binom.test</em> command, but we must include the <em>correct=F</em> option to get the Wilson interval.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="at">x=</span><span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel)[<span class="dv">2</span>],<span class="at">n=</span><span class="fu">sum</span>(<span class="fu">table</span>(msqol<span class="sc">$</span>fatiglevel)), <span class="at">correct=</span>F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1-sample proportions test without continuity correction

data:  table(msqol$fatiglevel)[2] out of sum(table(msqol$fatiglevel)), null probability 0.5
X-squared = 106.73, df = 1, p-value &lt; 2.2e-16
alternative hypothesis: true p is not equal to 0.5
95 percent confidence interval:
 0.1327152 0.2262628
sample estimates:
        p 
0.1746032 </code></pre>
</div>
</div>
<p>Note that the estimated proportion is the same as above, but the confidence interval has changed slightly. Note that a hypothesis test for the null hypothesis that the true probability of success is equal to 0.5 is also provided as in the <em>binom.test</em> command, but we can change this by adding another part to the command.</p>
</section>
<section id="two-sample-test-of-proportions" class="level3">
<h3 class="anchored" data-anchor-id="two-sample-test-of-proportions">Two sample test of proportions</h3>
<p>In lecture, we investigated the effect of a single nucleotide polymorphism on the probability of disease progression in patients with multiple sclerosis. The dataset for this analysis is the <em>2x2table.csv</em> dataset. In this dataset, we have the variable snp that equals 1 for patients with the SNP and 0 for patients without the SNP, and we have the variable prog that equals 1 for patients who progressed and 0 for patients who failed to progress.</p>
<p>Please load the 2x2table.csv dataset into R and call the dataset, snp_data.</p>
<p>Before we look at the data, we can complete the first three steps of our hypothesis test:</p>
<ol type="1">
<li><p>State estimand of interest: <span class="math inline">\(p_{SNP-}-p_{SNP+}\)</span></p></li>
<li><p>State the type of data: Dichotomous outcome, dichotomous predictor</p></li>
<li><p>Determine appropriate statistical method: Two sample test of proportions</p></li>
</ol>
<p>In this case, we would like to estimate the difference in the probability of progression patients without the SNP and those with the SNP. First, let’s look at a cross tabulation of the data. Create a table using <em>snp</em> as the row variable and <em>prog</em> as the column variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(snp_data<span class="sc">$</span>snp, snp_data<span class="sc">$</span>prog)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
      0   1
  0 103  13
  1  62  12</code></pre>
</div>
</div>
<p>Of those patients without the SNP (top row), 13 progressed, and 103 failed to progress. Of those patients with the SNP (bottom row), 12 progressed, and 62 failed to progress.</p>
<p>Now let’s look at a table of the row proportions. When we add the option 1 to the <em>prop.table</em>, we get the row proportions. If we use the option 2, we get column proportions. If we do not add an option to <em>prop.table</em>, we get total sample proportions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(snp_data<span class="sc">$</span>snp, snp_data<span class="sc">$</span>prog),<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   
            0         1
  0 0.8879310 0.1120690
  1 0.8378378 0.1621622</code></pre>
</div>
</div>
<p>Of those patients without the SNP, 0.112 progressed, and 0.888 failed to progress. Of those patients with the SNP, 0.162 progressed, and 0.838 failed to progress.</p>
<p>There are a number of ways to complete this analysis in R. The first is to complete a test of proportions using the <em>prop.test</em> command. This test provides you with the summary statistics as well as the p-value for the hypothesis test. The correct=FALSE option specifies that we are not using the continuity correction in our test. The default uses the continuity correction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">table</span>(snp_data<span class="sc">$</span>snp, snp_data<span class="sc">$</span>prog),<span class="at">correct=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  table(snp_data$snp, snp_data$prog)
X-squared = 0.99215, df = 1, p-value = 0.3192
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.0516337  0.1518201
sample estimates:
   prop 1    prop 2 
0.8879310 0.8378378 </code></pre>
</div>
</div>
<p>The output presented here provides the sample proportions in each group. R reports the proportion that failed to progress (<span class="math inline">\(prog=0\)</span>) rather than the proportion that progressed (<span class="math inline">\(prog=1\)</span>). The estimated difference in the proportion who failed to progress is <span class="math inline">\(\hat{q}_{SNP-}-\hat{q}_{SNP+}=\)</span> 0.888 <span class="math inline">\(-\)</span> 0.838= 0.05. Note that we use the notation <span class="math inline">\(\hat{q}\)</span> for the proportion who failed to progress as opposed to <span class="math inline">\(\hat{p}\)</span> which represented the proportion who progressed. The output also presents the Wald 95% confidence interval for the difference of the proportions (<span class="math inline">\(\hat{q}_{SNP-}-\hat{q}_{SNP+}\)</span>: -0.052, 0.152). Finally, R provides the two-sided hypothesis test p-value (<span class="math inline">\(p=\)</span> 0.319).</p>
<p>If we wanted R to report the proportion who progressed in the two groups we could use this command.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="fu">table</span>(snp_data<span class="sc">$</span>snp,(<span class="dv">1</span><span class="sc">-</span>snp_data<span class="sc">$</span>prog)),<span class="at">correct=</span>F)  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    2-sample test for equality of proportions without continuity correction

data:  table(snp_data$snp, (1 - snp_data$prog))
X-squared = 0.99215, df = 1, p-value = 0.3192
alternative hypothesis: two.sided
95 percent confidence interval:
 -0.1518201  0.0516337
sample estimates:
   prop 1    prop 2 
0.1120690 0.1621622 </code></pre>
</div>
</div>
<p>Note that the p-value and the conclusion is the same as above, but the confidence interval has the opposite sign. The sign of the confidence limits has changed because the estimated difference between the proportions is now the proportion that progressed in SNP- minus proportion that progressed in SNP+ <span class="math inline">\(\hat{p}_{SNP-}-\hat{p}_{SNP+}=\)</span> 0.05.</p>
<p>With this information, we can complete our analysis.</p>
<ol start="4" type="1">
<li>State estimate: <span class="math inline">\(\hat{p}_{SNP-}-\hat{p}_{SNP+}=\)</span> 0.05</li>
<li>Calculate 95% confidence interval and p-value (stat package): 95% CI: -0.052, 0.152; <span class="math inline">\(p=\)</span> 0.319</li>
<li>Write conclusion: Based on our sample, the range of plausible values for the difference in the proportions is -0.052 to 0.152. No difference between the groups is one of the plausible values.</li>
</ol>
</section>
<section id="chi-squared-test" class="level3">
<h3 class="anchored" data-anchor-id="chi-squared-test">Chi-squared test</h3>
<p>The more common way to test the same hypothesis is to use a chi-square test, and the chisq.test command will run the chi-square test. Again, the default uses the continuity correction, while the <em>correct=FALSE</em> option will turn it off:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">table</span>(snp_data<span class="sc">$</span>snp, snp_data<span class="sc">$</span>prog),<span class="at">correct=</span><span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  table(snp_data$snp, snp_data$prog)
X-squared = 0.99215, df = 1, p-value = 0.3192</code></pre>
</div>
</div>
<p>The results from above provide the p-value for the test of an association between the two measures (<span class="math inline">\(p=\)</span> 0.319). There is no estimate of the association from this command, but we will show how to get an estimate of the association from another command.</p>
</section>
<section id="fishers-exact-test" class="level3">
<h3 class="anchored" data-anchor-id="fishers-exact-test">Fisher’s exact test</h3>
<p>We can test the same hypothesis with Fisher’s exact test. The first three steps of the hypothesis test are the same as above, but we use the fisher.test command:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(<span class="fu">table</span>(snp_data<span class="sc">$</span>snp, snp_data<span class="sc">$</span>prog))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  table(snp_data$snp, snp_data$prog)
p-value = 0.3803
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.596721 3.896397
sample estimates:
odds ratio 
  1.529888 </code></pre>
</div>
</div>
<p>The results from above provide the p-value for the test of an association between the two measures (<span class="math inline">\(p=\)</span> 0.38).</p>
</section>
<section id="estimates-of-association" class="level3">
<h3 class="anchored" data-anchor-id="estimates-of-association">Estimates of association</h3>
<p>In order to calculate other estimates of the association when we have a dichotomous predictor and a dichotomous outcome, we can use the extensive set of commands in the epitools library. Within this library, there are separate commands for the calculation of the risk ratio and odds ratio. Note that we used the prop.test command to calculate the risk difference and the associated 95% confidence interval. To calculate risk ratio, we install the library and use <em>riskratio</em> command. For this command, we list the predictor (<em>snp</em>) as “x” and the outcome (<em>prog</em>) as “y”, and we get the following results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(<span class="at">x=</span>snp_data<span class="sc">$</span>snp,<span class="at">y=</span>snp_data<span class="sc">$</span>prog)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
         Outcome
Predictor   0  1 Total
    0     103 13   116
    1      62 12    74
    Total 165 25   190

$measure
         risk ratio with 95% C.I.
Predictor estimate     lower    upper
        0 1.000000        NA       NA
        1 1.446985 0.6984203 2.997861

$p.value
         two-sided
Predictor midp.exact fisher.exact chi.square
        0         NA           NA         NA
        1  0.3303927    0.3802594  0.3192177

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
</div>
<p>From this set of results, we get both the chi-squared test p-value (0.319) and Fisher’s exact test p-value (0.38). Further, we get the estimated risk ratio (1.45) and the associated 95% confidence interval (0.7, 3). Using these results, we can perform our analysis:</p>
<ol type="1">
<li>State estimand of interest: <span class="math inline">\(\frac{p_{SNP+}}{p_{SNP-}}\)</span>; <span class="math inline">\(H_0: \frac{p_{SNP+}}{p_{SNP-}}=1\)</span></li>
<li>State type of data: Dichotomous outcome, dichotomous predictor</li>
<li>Determine appropriate statistical test: Chi-squared test with risk ratio estimate</li>
<li>State estimate: <span class="math inline">\(\hat{RR}=\frac{\hat{p}_{SNP+}}{\hat{p}_{SNP-}}\)</span> = 1.45</li>
<li>Calculate 95% confidence interval and p-value (stat package): 95% CI: 0.7, 3; <span class="math inline">\(p=\)</span> 0.319</li>
<li>Write conclusion: Based on our sample, the range of plausible values for the risk ratio is 0.7 to 3. No difference between the groups is one of the plausible values.</li>
</ol>
<p>To calculate odds ratio, we can use the <em>oddsratio</em> command. For this command, we list the predictor as “x” and the outcome as “y”, and we get the following results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(<span class="at">x=</span>snp_data<span class="sc">$</span>snp,<span class="at">y=</span>snp_data<span class="sc">$</span>prog)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
         Outcome
Predictor   0  1 Total
    0     103 13   116
    1      62 12    74
    Total 165 25   190

$measure
         odds ratio with 95% C.I.
Predictor estimate    lower    upper
        0 1.000000       NA       NA
        1 1.531089 0.644222 3.615143

$p.value
         two-sided
Predictor midp.exact fisher.exact chi.square
        0         NA           NA         NA
        1  0.3303927    0.3802594  0.3192177

$correction
[1] FALSE

attr(,"method")
[1] "median-unbiased estimate &amp; mid-p exact CI"</code></pre>
</div>
</div>
<p>From this set of results, we get both the chi-squared test p-value (0.319) and Fisher’s exact test p-value (0.38). Further, we get the estimated odds ratio (1.53) and the associated 95% confidence interval (0.64, 3.62). Using these results, we can perform our analysis:</p>
<ol type="1">
<li>State estimand of interest: <span class="math inline">\(\frac{Odds_{SNP+}}{Odds_{SNP-}}\)</span>; <span class="math inline">\(H_0: OR = \frac{Odds_{SNP+}}{Odds_{SNP-}} =1\)</span></li>
<li>State type of data: Dichotomous outcome, dichotomous predictor</li>
<li>Determine appropriate statistical test: Chi-squared test with odds ratio estimate</li>
<li>State estimate: <span class="math inline">\(\hat{OR} = \frac{\hat{Odds}_{SNP+}}{\hat{Odds}_{SNP-}}=\)</span> 1.53</li>
<li>Calculate 95% confidence interval and p-value (stat package): 95% CI: 0.64, 3.62; <span class="math inline">\(p=\)</span> 0.319</li>
<li>Write conclusion: Based on our sample, the range of plausible values for the odds ratio is 0.64 to 3.62. No difference between the groups is one of the plausible values.</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>